export const ActionType = {
    TAKE_OFF_SAFELY: 'TAKE_OFF_SAFELY',
    LAND_SAFELY: 'LAND_SAFELY',
    FLY_UPWARD: 'FLY_UPWARD',
    FLY_DOWNWARD: 'FLY_DOWNWARD',
    FLY_TO_LEFT: 'FLY_TO_LEFT',
    FLY_TO_RIGHT: 'FLY_TO_RIGHT',
    ROTATE_LEFT: 'ROTATE_LEFT',
    ROTATE_RIGHT: 'ROTATE_RIGHT'
};